import os
from dotenv import load_dotenv
load_dotenv()
BOT_TOKEN=os.getenv('BOT_TOKEN','').strip()
ADMIN_IDS={int(x.strip()) for x in os.getenv('ADMIN_IDS','').split(',') if x.strip().isdigit()}
DB_PATH=os.getenv('DB_PATH','bot.db').strip()
LOG_LEVEL=os.getenv('LOG_LEVEL','INFO').upper()
COPY_SCAN_INTERVAL=int(os.getenv('COPY_SCAN_INTERVAL','10'))
TRADE_SCAN_INTERVAL=int(os.getenv('TRADE_SCAN_INTERVAL','30'))
COPY_PER_TRADE_PERCENT=float(os.getenv('COPY_PER_TRADE_PERCENT','10'))
DEFAULT_SLIPPAGE_BPS=int(os.getenv('DEFAULT_SLIPPAGE_BPS','100'))
MIN_TRADE_USD=float(os.getenv('MIN_TRADE_USD','1'))
MAX_TRADE_USD=float(os.getenv('MAX_TRADE_USD','10000'))
DEFAULT_MAX_COPY_PERCENT=float(os.getenv('DEFAULT_MAX_COPY_PERCENT','100'))
AUTO_TAKE_PROFIT_PCT=float(os.getenv('AUTO_TAKE_PROFIT_PCT','50'))
AUTO_STOP_LOSS_PCT=float(os.getenv('AUTO_STOP_LOSS_PCT','10'))
AUTO_TRADE_ALLOCATION_PCT=float(os.getenv('AUTO_TRADE_ALLOCATION_PCT','10'))
SOLANA_RPC_URL=os.getenv('SOLANA_RPC_URL','https://api.mainnet-beta.solana.com').strip()
JUPITER_API_KEY=os.getenv('JUPITER_API_KEY','').strip()
HELIUS_API_KEY=os.getenv('HELIUS_API_KEY','').strip()
HELIUS_RPC_URL=os.getenv('HELIUS_RPC_URL','https://mainnet.helius-rpc.com/?api-key={HELIUS_API_KEY}').strip()
ALCHEMY_API_KEY=os.getenv('ALCHEMY_API_KEY','').strip()
ALCHEMY_ETH_RPC_URL=os.getenv('ALCHEMY_ETH_RPC_URL','https://eth-mainnet.g.alchemy.com/v2/{ALCHEMY_API_KEY}').strip()
BSC_RPC_URL=os.getenv('BSC_RPC_URL','https://bsc-dataseed.binance.org').strip()
COINGECKO_API_KEY=os.getenv('COINGECKO_API_KEY','').strip()
COINGECKO_API_BASE=os.getenv('COINGECKO_API_BASE','https://api.coingecko.com/api/v3').strip()
ZEROX_API_KEY=os.getenv('ZEROX_API_KEY','').strip()
BSCSCAN_API_KEY=os.getenv('BSCSCAN_API_KEY','').strip()
DEPOSIT_SCAN_INTERVAL=int(os.getenv('DEPOSIT_SCAN_INTERVAL','20'))
AUTO_SCAN_INTERVAL=int(os.getenv('AUTO_SCAN_INTERVAL','30'))
DEPOSIT_SOL_ADDRESS=os.getenv('DEPOSIT_SOL_ADDRESS','').strip()
DEPOSIT_ETH_ADDRESS=os.getenv('DEPOSIT_ETH_ADDRESS','').strip()
DEPOSIT_BSC_ADDRESS=os.getenv('DEPOSIT_BSC_ADDRESS','').strip()
SOL_DEPOSIT_ADDRESSES=os.getenv('SOL_DEPOSIT_ADDRESSES','').strip()
ETH_DEPOSIT_ADDRESSES=os.getenv('ETH_DEPOSIT_ADDRESSES','').strip()
BNB_DEPOSIT_ADDRESSES=os.getenv('BNB_DEPOSIT_ADDRESSES','').strip()
SOL_DEPOSIT_CONFIRMATIONS=int(os.getenv('SOL_DEPOSIT_CONFIRMATIONS','1'))
ETH_DEPOSIT_CONFIRMATIONS=int(os.getenv('ETH_DEPOSIT_CONFIRMATIONS','3'))
BNB_DEPOSIT_CONFIRMATIONS=int(os.getenv('BNB_DEPOSIT_CONFIRMATIONS','3'))
ENABLE_REAL_TRADING=os.getenv('ENABLE_REAL_TRADING','false').strip().lower()=='true'
EXECUTION_PRIVATE_KEY=os.getenv('EXECUTION_PRIVATE_KEY','').strip()

def validate_config():
    missing=[]
    if not BOT_TOKEN: missing.append('BOT_TOKEN')
    if not ADMIN_IDS: missing.append('ADMIN_IDS')
    if missing: raise RuntimeError('Missing .env values: '+', '.join(missing))
